Set AssetsPickerViewController minimum version
Our build failed with message:

"Plugins/cordova-plugin-wm-file/WMFilePickerPlugin.swift:175:29: error: value of type 'AssetsPickerConfig' has no member 'assetsMaximumSelectionCount'
        picker.pickerConfig.assetsMaximumSelectionCount = multiple ? Int.max : 1;"

The method assetsMaximumSelectionCount was added in 2.7.5:

https://github.com/DragonCherry/AssetsPickerViewController/compare/2.7.4...2.7.5

We now solved this by Flushing the pod cache on the build-server, but it would be better if correct minimum-version is specified.